apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# backstage
  - ./backstage/backstage-deployment.yaml  
  - ./backstage/backstage-sa.yaml  
  - ./backstage/postgres-deployment.yaml
  - ./backstage/backstage-app-config.yaml
  - ./backstage/backstage-ocm-role.yaml

#keycloack
  - ./keycloack/keycloack.yaml
  - ./keycloack/keycloackclient.yaml  
  - ./keycloack/keycloackuser.yaml  
  - ./keycloack/realm.yaml
