apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# ##acm
#   - ./acm/multiclusterhub.yaml
# backstage
  - ./backstage-deployment.yaml  
  - ./backstage-sa.yaml  
  - ./postgres-deployment.yaml
  - ./backstage-app-config.yaml
## #kepler
#   - ./kepler/kepler-config.yaml
#   - ./kepler/kepler-deployment.yaml  
#   - ./kepler/kepler-sa.yaml
