kind: KeycloakRealm
apiVersion: keycloak.org/v1alpha1
metadata:
  name: keycloakrealm
  namespace: sso
  labels:
    app: sso
    realm: basic
spec:
  realm:
    id: basic
    realm: basic
    enabled: true
    displayName: Basic Realm
  instanceSelector:
    matchLabels:
      app: sso

