apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: rhdh
    server: 'https://kubernetes.default.svc'

  source:
    chart: redhat-developer-hub
    repoURL: 'https://charts.openshift.io'
    targetRevision: 0.1.0
    helm:
      releaseName: rhdh
  project: rhdh
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
