apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rhdh
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/Janus-france-ssa/janus-gitops.git 
  - https://charts.openshift.io
status: {}
